function jslog_init(e,o){try{var n=0
if(e==JSLOG_LEV_AUTO){var t=document.getElementById(JSLOG_ID_CFG),l=document.getElementById(JSLOG_ID_LOGLEV)
if(null!=t){var r=t.value
if(null!=r&&""!=r){var i=JSON.parse(r)
e=i.iLogLev,void 0==o&&(o=new Object),o.bLogTime=i.bLogTime,o.szPathImg=i.szPathImg,o.szSize=i.szSize}else e=JSLOG_LEV_URL}else null!=l?(val=l.value,e=""!=val?parseInt(l.value):JSLOG_LEV_URL):e=JSLOG_LEV_URL}if(e==JSLOG_LEV_URL){var a=function(e){if(e=new RegExp("[?&]"+encodeURIComponent(e)+"=([^&]*)").exec(location.search))return decodeURIComponent(e[1])}(JSLOG_LEV_URL_PAR),s=JSLOG_LEV_URL_PAR+"="
if(void 0!==a)window.name=s+a
else{var j=window.name
j.indexOf(s)>-1&&(a=parseInt(j.substr(s.length)))}n=void 0!==a?a:0}else n=parseInt(e)
jj_consoleStart(n,o),null!=o&&null!=o.szSize&&jslogSetSize(o.szSize)}catch(e){console.error(e)}}function jslogLevSet(e){jj_var.iLogLev=e,0==e?jslog_end():jj_var.console&&(jj_var.console.selectLogLev.selectedIndex=e,jj_setTitle(e)),jj_saveCfg()}function jj_setTitle(e){var o='<a style="margin-left:30px" class="tipLink" href="'+JSU_URL_ALL_SAMPLE+'" target="_blank">JSU Sample (by F. Levis)</a>',n="Level="+e+"  "+o
jj_var.console.labelTitle.innerHTML=n}function jslogSetSize(e){null!=jj_var.console&&jj_var.console.setSize(e)}function jslogSetTop(e){null!=jj_var.console&&null!=jj_var.console.window&&(jj_var.console.window.style.top=e+"px")}function jslogClear(){jj_var.console&&jj_var.console.clearWindow()}function jslogGetLogLev(){return jj_var.iLogLev}function jslogGetOpt(){return{iLogLev:jj_var.iLogLev,bLogTime:jj_var.bLogTime,szPathImg:jj_var.szPathImg,szSize:jj_var.szSize}}function jslogObj(e,o,n,t){void 0!=t&&null!=t||(t=!1)
var l=t?0:2,r=t?": ":"\n"
return isLogLevEnable(e)&&jj_var.console&&jj_var.console.send(e,o+r+JSON.stringify(n,null,l)),0}function jslogHtml(e,o,n,t){if(isLogLevEnable(e)&&void 0!=jj_var.console){void 0==t&&(t=new Object),void 0==t.iColNum&&(t.iColNum=JSLOG_DEF_DOM_EL_COL_NUM),void 0==t.iRowNum&&(t.iRowNum=jj_getHtmlRowNum(n))
return jslog(e,o+':<BR><textarea style="width: '+JSLOG_DEF_TEXT_BOX_WIDTH+'"; height: '+JSLOG_DEF_TEXT_BOX_HEIGHT+'";"  rows="'+t.iRowNum+'" cols="'+t.iColNum+'">'+n+"</textarea><BR>"),0}}function jslogDomEl(e,o,n,t){if(null!=n&&0!=n&&isLogLevEnable(e)&&void 0!=jj_var.console){void 0==t&&(t=new Object),void 0==t.iColNum&&(t.iColNum=JSLOG_DEF_DOM_EL_COL_NUM),void 0==t.style&&(t.style=JSLOG_STYLE.NONE)
for(var l="nodeName="+n.nodeName+"\n",r=0;r<n.attributes.length;r++){var i=n.attributes[r]
l+=i.name+"="+i.value+"\n"}if(l+="outerHTML="+jj_replaceAll(n.outerHTML,"><",">\n<"),t.style!=JSLOG_STYLE.NONE){var a=n.style,s=window.getComputedStyle(n,null)
l+="\n\n--------------------------------------- ",t.style==JSLOG_STYLE.ONLY_MEANINGFUL?l+="meaningful style \n":l+="style \n"
for(x in a){var j=!0
if(t.style==JSLOG_STYLE.ONLY_MEANINGFUL&&(0==a[x]&&void 0==s[x]||0==a[x]&&void 0==s[x]||""==a[x]&&""==s[x]||x.indexOf("animation")>=0||x.indexOf("accelerator")>=0||void 0!=a[x]&&"function"==typeof a[x])&&(j=!1),j){var c=a[x]
0!=c&&""!=c||(c=s[x]),l+="  "+x+" = '"+c+"'\n"}}}void 0==t.iRowNum&&(t.iRowNum=jj_getHtmlRowNum(l))
return jslog(e,o+':<BR><textarea rows="'+t.iRowNum+'" cols="'+t.iColNum+'" readonly>'+l+"</textarea><BR>"),0}}function jslogDomElById(e,o,n,t){return jslogDomEl(e,o,document.getElementById(n),t)}function json2jslogStr(e){var o=jj_replaceAll(JSON.stringify(e),"},","} ,\n  ")
return o=jj_replaceAll(o,":[",":\n[\n  "),o=jj_replaceAll(o,"[{","[\n  {"),jj_replaceAll(o,"}]","}\n]\n  ")}function jslogJson(e,o,n){return isLogLevEnable(e)&&jj_var.console.send(e,o+"\n"+json2jslogStr(n)),0}function jslogElapsedTime(e,o,n){if(isLogLevEnable(e)&&jj_var.console){var t=new Date,l=t.getTime()-n.getTime(),r=l>1e3?l/1e3+" sec":l+" msec"
jj_var.console.send(e,o+r)}return 0}function jslog(e,o){return isLogLevEnable(e)&&jj_var.console&&jj_var.console.send(e,o),0}function jslog_end(){jj_var.console&&jj_var.console.killWindow()}function isLogLevEnable(e){return(jj_var.iLogLev&e||0==e)&&null!=jj_var.console}function jj_getHtmlRowNum(e){if("string"!=typeof e)return 0
var o=1+(e.match(/\n/g)||[]).length
return o>JSLOG_MAX_TEXT_BOX_ROW_NUM&&(o=JSLOG_MAX_TEXT_BOX_ROW_NUM),o}function jj_replaceAll(e,o,n){if(void 0===e)return""
for(;e.indexOf(o)>-1;)e=e.replace(o,n)
return e}function jj_saveCfg(){var e=document.getElementById(JSLOG_ID_CFG)
if(null!=e){var o={iLogLev:jj_var.iLogLev,bLogTime:jj_var.bLogTime,szPathImg:jj_var.szPathImg,szSize:jj_var.szSize},n=JSON.stringify(o,null,0)
e.value=n}else{var e=document.getElementById(JSLOG_ID_LOGLEV)
null!=e&&(e.value=jj_var.iLogLev)}}function jj_consoleStart(e,o){var n=JSLOG_SIZE_DEF
jslog_end(),jj_var.iLogLev=e,0!=jj_var.iLogLev&&(void 0!=o&&(void 0!=o.szPathImg&&(jj_var.szPathImg=o.szPathImg),void 0!=o.bLogTime&&(jj_var.bLogTime=o.bLogTime)),jj_var.console={debugging_on:!1,window:null,viewport:null,buffer:"",debugVisible:!1,arBtnDebug:new Array,init:function(){if(document.getElementsByTagName&&document.getElementById&&document.createElement&&document.createTextNode){void 0!==document.getElementsByTagName("body")[0]&&(jj_var.console.createWindow(),jj_var.console.getCookie(),jj_var.console.debugging_on=!0,jj_var.console.setSize(n))}},createWindow:function(){jj_var.console.window=document.createElement("div"),jj_var.console.window.style.background="#000",jj_var.console.window.style.font='9pt "Lucida Grande", "Lucida Sans Unicode", sans-serif',jj_var.console.window.style.padding="2px",jj_var.console.window.style.position="absolute",jj_var.console.window.style.top=WIN_JSLOG_TOP,jj_var.console.window.style.left="0px",jj_var.console.window.style.height=WIN_JSLOG_H,jj_var.console.window.style.zIndex="100",jj_var.console.window.style.minHeight="40px",jj_var.console.window.style.width=WIN_JSLOG_W,jj_var.console.window.style.minWidth="150px"
var e=document.createElement("span")
e.style.border="1px solid #000",e.style.cursor="pointer",e.style.color="#000",e.style.display="block",e.style.lineHeight=".5em",e.style.padding="0 0 3px",e.style.position="absolute",e.style.top="4px",e.style.right="4px",e.setAttribute("title","Close jj_var.console Debugger"),e.appendChild(document.createTextNode("x")),jj_var.console.addEvent(e,"click",function(){jj_var.console.killWindow()}),jj_var.console.window.appendChild(e)
var o=document.createElement("div")
o.style.position="absolute",o.style.bottom="3px",o.style.right="3px"
var n=document.createElement("span")
n.style.border="5px solid #ccc",n.style.borderLeftColor=n.style.borderTopColor="#000",n.style.cursor="pointer",n.style.color="#ccc",n.style.display="block",n.style.height="0",n.style.width="0",n.style.overflow="hidden",n.setAttribute("title","Resize the jj_var.console Debugger"),"undefined"!=typeof Drag&&(n.xFrom=0,n.yFrom=0,Drag.init(n,null,null,null,null,null,!0,!0),n.onDrag=function(e,o){jj_var.console.resizeX(e,this),jj_var.console.resizeY(o,this),jj_var.console.adjustViewport()},n.onDragEnd=function(){jj_var.console.setCookie()},o.appendChild(n),jj_var.console.window.appendChild(o))
var t=document.createElement("h3")
t.className="jslog",t.style.textAlign="left",jj_var.console.appendAllBtn(t,!1),t.appendChild(jj_var.console.getGroupSep("    ")),jj_var.console.labelTitle=document.createElement("label"),jj_var.console.labelTitle.className="jslog",jj_setTitle(jj_var.iLogLev),t.appendChild(jj_var.console.labelTitle),jj_var.console.window.appendChild(t)
var l=document.createElement("div")
l.className="jslogFooter",jj_var.console.appendAllBtn(l,!0),jj_var.console.window.appendChild(l),jj_var.console.viewport=document.createElement("pre"),jj_var.console.viewport.style.border="1px solid #ccc",jj_var.console.viewport.style.color="#ebebeb",jj_var.console.viewport.style.color="white",jj_var.console.viewport.style.backgroundColor="black",jj_var.console.viewport.style.textAlign="left",jj_var.console.viewport.style.fontSize="1.2em",jj_var.console.viewport.style.margin="0",jj_var.console.viewport.style.padding="0 3px",jj_var.console.viewport.style.position="absolute",jj_var.console.viewport.style.top="25px",jj_var.console.viewport.style.left="2px",jj_var.console.viewport.style.overflow="auto",jj_var.console.adjustViewport(),jj_var.console.window.appendChild(jj_var.console.viewport),document.getElementsByTagName("body")[0].appendChild(jj_var.console.window),"undefined"!=typeof Drag&&(Drag.init(t,jj_var.console.window),jj_var.console.window.onDragEnd=function(){jj_var.console.setCookie()})},resizeX:function(e,o){var n=parseInt(jj_var.console.window.style.width),t=Math.abs(n-(e-o.xFrom))+"px"
parseInt(t)<parseInt(jj_var.console.window.style.minWidth)&&(t=jj_var.console.window.style.minWidth),jj_var.console.window.style.width=t,o.xFrom=e},resizeY:function(e,o){var n=parseInt(jj_var.console.window.style.height),t=Math.abs(n-(e-o.yFrom))+"px"
parseInt(t)<parseInt(jj_var.console.window.style.minHeight)&&(t=jj_var.console.window.style.minHeight),jj_var.console.window.style.height=t,o.yFrom=e},adjustViewport:function(){jj_var.console.viewport.style.width=parseInt(jj_var.console.window.style.width)-8+"px",jj_var.console.viewport.style.height=parseInt(jj_var.console.window.style.height)-50+"px"},send:function(e,o){if(e==JSLOG_ERR&&console.error(o),o+="<br/>",o.indexOf("<textarea rows")<0)for(;o.indexOf("\n")>-1;)o=o.replace("\n","<br/>")
var n=""
if(jj_var.bLogTime){var t=new Date
n=jj_var.console.num2StrPad(t.getHours(),"0",2)+":"+jj_var.console.num2StrPad(t.getMinutes(),"0",2)+":"+jj_var.console.num2StrPad(t.getSeconds(),"0",2)+"."+jj_var.console.num2StrPad(t.getMilliseconds(),"0",3)+" "}null!=e&&(o=n+"["+e+"] "+o),null==jj_var.console.viewport?jj_var.console.buffer+=o:(jj_var.console.viewport.innerHTML+=o,jj_var.console.scrollWithIt())},sendBuffer:function(){null==jj_var.console.viewport?jj_var.console.timer=window.setTimeout("jj_var.console.sendBuffer()",500):(jj_var.console.viewport.innerHTML+=jj_var.console.buffer,jj_var.console.scrollWithIt(),jj_var.console.killTimer())},scrollWithIt:function(){jj_var.console.viewport.scrollTop=jj_var.console.viewport.scrollHeight},killWindow:function(){jj_var.console.window.parentNode.removeChild(jj_var.console.window),jj_var.console.debugging_on=!1,jj_var.console=null,window.name=JSLOG_LEV_URL_PAR+"=0"},setCookie:function(){var e=jj_var.console.window.style.top+" "+jj_var.console.window.style.left,o=jj_var.console.window.style.height+" "+jj_var.console.window.style.width
document.cookie="jj_var.console="+escape(e+" "+o)},getCookie:function(){if(document.cookie){var e=document.cookie,o=e.indexOf("jj_var.console=")
if(-1!=o){var n=o+"jj_var.console=".length,t=e.indexOf(";",n),l=-1!=t?e.substring(n,t):e.substring(n)
l=unescape(l)
var r=l.split(" ")
jj_var.console.window.style.top=r[0],jj_var.console.window.style.left=r[1],jj_var.console.window.style.height=r[2],jj_var.console.window.style.width=r[3],jj_var.console.adjustViewport()}}},timer:null,killTimer:function(){clearTimeout(jj_var.console.timer)},addEvent:function(e,o,n){e.addEventListener?e.addEventListener(o,n,!1):e.attachEvent&&(e["e"+o+n]=n,e[o+n]=function(){e["e"+o+n](window.event)},e.attachEvent("on"+o,e[o+n]))},removeEvent:function(e,o,n){e.removeEventListener?e.removeEventListener(o,n,!1):e.detachEvent&&(e.detachEvent("on"+o,e[o+n]),e[o+n]=null,e["e"+o+n]=null)},appendAllBtn:function(e,o){var n=new Array
e.appendChild(jj_var.console.getImgPos("arrowTopLeft.jpg","Move JSConsole to TOP LEFT CORNER",JSLOG_POS_TOPLEFT)),e.appendChild(jj_var.console.getImgPos("arrowBottomRight.jpg","Move JSConsole to BOTTOM RIGHT LEFT CORNER",JSLOG_POS_BOTTOMRIGHT)),e.appendChild(jj_var.console.getImgPos("arrowLeft.jpg","Move JSConsole to LEFT SIDE",JSLOG_POS_LEFT)),e.appendChild(jj_var.console.getImgPos("arrowRight.jpg","Move JSConsole to the RIGHT SIDE",JSLOG_POS_RIGTH)),e.appendChild(jj_var.console.getImgPos("arrowTop.jpg","Move JSConsole to the TOP",JSLOG_POS_TOP)),e.appendChild(jj_var.console.getImgPos("arrowBottom.jpg","Move JSConsole to the BOTTOM",JSLOG_POS_BOTTOM)),e.appendChild(jj_var.console.getGroupSep(""))
var t=new Array
t.push(["XS",30,"Size SX",function(){jj_var.console.setSize(JSLOG_SIZE.XS)}]),t.push(["S",30,"Size S",function(){jj_var.console.setSize(JSLOG_SIZE.S)}]),t.push(["M",30,"Size M",function(){jj_var.console.setSize(JSLOG_SIZE.M)}]),t.push(["L",30,"Size L",function(){jj_var.console.setSize(JSLOG_SIZE.L)}]),t.push(["XL",30,"Size XL",function(){jj_var.console.setSize(JSLOG_SIZE.XL)}])
for(var l=0;l<t.length;l++){var r=jj_var.console.getBtn(t[l])
e.appendChild(r),e.appendChild(jj_var.console.getBtnSep())}e.appendChild(jj_var.console.getGroupSep("")),n.push(["Clear",60,"Clear the Window",function(){jj_var.console.clearWindow()}]),n.push(["Delimiter",70,"Add a Separator Delimet",function(){jj_var.console.sendDelimiter()}]),jj_var.console.isIE()?n.push(["CopyToClipboard",120,"Copy To Clipboard All the  contain of the  Window",function(){jj_var.console.copy2Clipboard()}]):n.push(["SelectAll",70,"Select ALL",function(){jj_var.console.selectAll()}])
for(var l=0;l<n.length;l++){var r=jj_var.console.getBtn(n[l])
e.appendChild(r),e.appendChild(jj_var.console.getBtnSep())}e.appendChild(jj_var.console.getGroupSep(""))
var i=jj_var.console.getBtn(["Show debug Fields",150,'Show hidden fields having class="debug" or id="debug"',function(){var e,o
jj_var.console.debugVisible?(jj_var.console.debugVisible=!1,e="Show "+JSLOG_ID_DEBUG+" Fields",o='Show hidden fields having class="'+JSLOG_ID_DEBUG+'" or id="'+JSLOG_ID_DEBUG+'"'):(jj_var.console.debugVisible=!0,e="Hide "+JSLOG_ID_DEBUG+"Fields",o='Hide again Debug fields having class="'+JSLOG_ID_DEBUG+'" or id="'+JSLOG_ID_DEBUG+'"')
for(var n=0;n<jj_var.console.arBtnDebug.length;n++){var t=jj_var.console.arBtnDebug[n]
t.value=e,t.title=o}for(var l=["SPAN","DIV","TABLE"],r=0;r<l.length;r++)for(var i=document.getElementsByTagName(l[r]),n=0;n<i.length;n++){var a=i[n]
"debug"!=a.id&&"debug"!=a.className||(jj_var.console.debugVisible?a.style.display="block":a.style.display="none")}}])
e.appendChild(i),jj_var.console.arBtnDebug.push(i),e.appendChild(jj_var.console.getGroupSep("")),e.appendChild(jj_var.console.getGroupSep(""))
var a=jj_var.console.getBtn(["CLOSE JSLOG",120,"Close JSLog Window",function(){jslog_end()}])
if(e.appendChild(a),o){var s=document.createElement("label")
s.className="jslogFooter",s.innerHTML="SETTINGS: ",e.appendChild(s)
var j=document.createElement("select")
j.className="jslog"
for(var l=0;l<=31;l++){var c="LogLevel="+l
0==l&&(c="CLOSE JSLOG")
var _=new Option(c,l)
_.dv=c,_.selected=jj_var.iLogLev==l,j[j.length]=_}jj_var.console.addEvent(j,"change",function(){jslogLevSet(this.selectedIndex)}),e.appendChild(j),jj_var.console.selectLogLev=j
var d=document.createElement("select")
d.className="jslog"
for(var v=[["0","NO Time"],["1","Log Time"]],l=0;l<v.length;l++){var c=v[l][1],_=new Option(c,v[l][0])
_.dv=c,_.selected=!jj_var.bLogTime&&0==l||jj_var.bLogTime&&1==l,d[d.length]=_}jj_var.console.addEvent(d,"change",function(){jj_var.bLogTime=1==this.selectedIndex,jj_saveCfg()}),e.appendChild(d)}},sendDelimiter:function(){jj_var.console.send(null,JSLOG_DELIMITER)},selectAll:function(){if(document.selection){var e=document.body.createTextRange()
e.moveToElementText(jj_var.console.window),e.select()}else if(window.getSelection){var e=document.createRange()
e.selectNode(jj_var.console.window),window.getSelection().addRange(e)}},copy2Clipboard:function(){for(var e=0,o=""+jj_var.console.viewport.innerHTML;o.indexOf("<BR>")>-1;)o=o.replace("<BR>","\n"),e++
for(;o.indexOf("<br>")>-1;)o=o.replace("<br>","\n"),e++
var n=document.createElement("TextArea")
if(n.innerText=o,void 0===n.createTextRange)return void alert("copy2Clipboard NOT supported for This Browser - Supported Browser for COPY to Clipboard: IE.To Copy to Clipboard Please use SelectAll or CTRL-C  CTRL-V")
Copied=n.createTextRange(),Copied.execCommand("RemoveFormat"),Copied.execCommand("Copy")},isIE:function(){try{return"Microsoft Internet Explorer"==navigator.appName||"Netscape"==navigator.appName&&null!=new RegExp("Trident/.*rv:([0-9]{1,}[.0-9]{0,})").exec(navigator.userAgent)}catch(e){return!1}},getBtn:function(e){var o=document.createElement("input")
return o.className="jslogButton",o.setAttribute("type","button"),o.setAttribute("value",e[0]),o.style.width=e[1]+"px",o.setAttribute("title",e[2]),jj_var.console.addEvent(o,"click",e[3]),o},getTxtSep:function(e){var o=document.createElement("span")
return o.style.color="#ffffff",o.style.fontWeight="bold",o.style.padding="0 2px 0px 10px",o.style.textAlign="right",o.appendChild(document.createTextNode(e)),o},getBtnSep:function(){var e=document.createElement("span")
return e.style.color="#ffffff",e.style.padding="0 3px 0px 0px",e},getGroupSep:function(){var e=document.createElement("span")
return e.style.color="#ffffff",e.style.padding="0 10px 0px 0px",e},getImgPos:function(e,o,n){var t=document.createElement("img")
return t.style.padding="0px 2px",t.style.cursor="pointer",t.src=jj_var.szPathImg+e,t.height=15,t.width=15,t.align="top",t.title=o,t.style.border="1px solid black",jj_var.console.addEvent(t,"mouseenter",function(){this.style.border="1px solid yellow"}),jj_var.console.addEvent(t,"mouseleave",function(){this.style.border="1px solid black"}),jj_var.console.addEvent(t,"click",function(){jj_var.console.setPos(n)}),t},setSize:function(e){jj_var.szSize=e,jj_saveCfg()
var o=0,n=0,t=0,l=0
void 0!==window.innerHeight?(o=window.innerHeight-30,n=window.innerWidth-30):(o=window.screen.height-150,n=window.screen.width-30),e==JSLOG_SIZE.XS?(t=1100,l=150):e==JSLOG_SIZE.S?(l=parseInt(.3*o),t=parseInt(.8*n)):e==JSLOG_SIZE.M?(l=parseInt(.5*o),t=parseInt(1*n)):e==JSLOG_SIZE.L?(l=parseInt(.6*o),t=parseInt(1*n)):e==JSLOG_SIZE.XL&&(jj_var.console.window.style.top="0px",jj_var.console.window.style.left="0px",l=parseInt(1*o),t=parseInt(1*n)),t<1100&&(t=1100),jj_var.console.window.style.width=t+"px",jj_var.console.window.style.height=l+"px",jj_var.console.adjustViewport()},setPos:function(e){var o=0,n=0
void 0!==window.innerHeight?(o=window.innerHeight-50,n=window.innerWidth-150):(o=window.screen.height-100,n=window.screen.width-200),e==JSLOG_POS_TOPLEFT?(jj_var.console.window.style.top="0px",jj_var.console.window.style.left="0px"):e==JSLOG_POS_BOTTOMRIGHT?(jj_var.console.window.style.top=o+"px",jj_var.console.window.style.left=n+"px"):e==JSLOG_POS_TOP?jj_var.console.window.style.top="0px":e==JSLOG_POS_BOTTOM?jj_var.console.window.style.top=o+"px":e==JSLOG_POS_LEFT?jj_var.console.window.style.left="0px":e==JSLOG_POS_RIGTH&&(jj_var.console.window.style.left=n+"px")},clearWindow:function(){jj_var.console.viewport.innerHTML=""},num2StrPad:function(e,o,n){var t=n-e.toString().length+1
return Array(+(t>0&&t)).join("0")+e}},jj_var.console.init(),o&&o.iTop&&jslogSetTop(o.iTop))}var JSLOG_ERR=0,JSLOG_INFO=1,JSLOG_DEBUG=2,JSLOG_TRACE=4,JSLOG_TEST=8,JSLOG_JSU=16,JSLOG_BASE=JSLOG_JSU,JSLOG_DUMP=JSLOG_TEST,JSLOG_CORE=JSLOG_JSU,JSLOG_ID_CFG="jslogCfg",JSLOG_ID_LOGLEV="jslogLev",JSLOG_LEV_AUTO="AUTO_DETECT",JSLOG_LEV_URL="URL",JSLOG_LEV_URL_PAR="jslog",JSLOG_ID_DEBUG="debug",JSLOG_DEF_LOG_TIME=!1,JSLOG_DEF_PATH_IMG="../../images/"
"undefined"!=typeof JSU_PATH_IMG&&(JSLOG_DEF_PATH_IMG=JSU_PATH_IMG)
var JSLOG_FUN_START="-------------------- START",JSLOG_FUN_END="-------------------- END",JSLOG_FILE_START=" ============================= START",JSLOG_FILE_END=" ============================= END",JSLOG_DELIMITER='<span style="color: #f00">-----------------------------------------------------------------------------------------------------------------------</span>',JSLOG_DEF_DOM_EL_COL_NUM=150,JSLOG_MAX_TEXT_BOX_ROW_NUM=10,JSLOG_DEF_TEXT_BOX_WIDTH="800px",JSLOG_DEF_TEXT_BOX_HEIGHT="300px",JSU_URL_ALL_SAMPLE="https://rawgit.com/FedericoLevis/JSU/master/samples/AllSamples.html",JSLOG_POS_TOPLEFT="TopLeft",JSLOG_POS_BOTTOMRIGHT="BottomRight",JSLOG_POS_TOP="Top",JSLOG_POS_LEFT="Left",JSLOG_POS_RIGTH="Right",JSLOG_POS_BOTTOM="Bottom",JSLOG_SIZE={XS:"XS",S:"S",M:"M",L:"L",XL:"XL"},JSLOG_STYLE={NONE:"NONE",ONLY_MEANINGFUL:"ONLY_MEANINGFUL",ALL:"ALL"},WIN_JSLOG_TOP="370px",JSLOG_SIZE_DEF=JSLOG_SIZE.L,WIN_JSLOG_H="400px",WIN_JSLOG_W="1200px",jj_var={iLogLev:0,bLogTime:JSLOG_DEF_LOG_TIME,szPathImg:JSLOG_DEF_PATH_IMG,szSize:JSLOG_SIZE_DEF,console:null}
